### ISSUE TITLE
Information Card Shape 2

### ISSUE THREAD

**Issue by hamzahalilovic** [prifina/app-desktop#96]
<img width="204" alt="Screenshot 2020-11-05 at 15 38 49" src="https://user-images.githubusercontent.com/26879042/98254959-2bbb4b80-1f7d-11eb-8314-80b9aa892c65.png">

**Information Card Shape 2**

Currently, the 4 sections that the user can fill out are: basic information, geographic information, education information, household information.

**Includes:** Text Fields

**Relevant user story:** [User story](https://docs.google.com/document/d/1J5iiOgJnjcFXOFnN11Ra7lGb-JSI9clSLA899GNJC3o/edit)

**Visual component design:** [Figma file](https://www.figma.com/file/cdQJSNK0F9OF6PtLOcMBk9/A1.3.-Data-Console-v.MVP?node-id=7%3A30)

**Specifications:**

**Comment by mmlampinen** [comment]
@hamzahalilovic I was testing how transferring works between the repos, but it seems like transferring from app-desktop -> apps removes all the labels, milestones etc. Do you know if there's anyway to avoid this, or if its just something we have to accept as we move all the issues to the 'apps' repo? Because e.g. all the data console issues should be there as the data console is an 'app'.

**Comment by hamzahalilovic** [comment]
@mmlampinen Yeah, as you see I have done the same. I will try to find a way to transfer them with all the labels, if it can't be done I'll do it the hard way :)
